[build]
  publish = "dist"
  command = "./scripts/netlify-build.sh"

[build.environment]
  NODE_VERSION = "18"
  SENTRY_SKIP_AUTO_RELEASE = "true"
  SENTRY_DISABLE_AUTO_UPLOAD = "true"

# Explicitly disable Sentry plugin
[[plugins]]
  package = "@sentry/netlify-build-plugin"

[plugins.inputs]
  disable = true

# SPA redirect for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdn.jsdelivr.net; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https://*.supabase.co wss://*.supabase.co https://api.twilio.com https://js.stripe.com https://*.ingest.us.sentry.io; frame-src 'self' https://js.stripe.com; object-src 'none'; base-uri 'self';"
    X-Robots-Tag = "noindex, nofollow, nosnippet, noarchive, noimageindex"