// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cjxejmljovszxuleibqn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNqeGVqbWxqb3Zzenh1bGVpYnFuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4ODcxMzEsImV4cCI6MjA2OTQ2MzEzMX0.SxVn2huG_XM1IOxgMqQbgqe6SFBahcLvY5LOBjjlVMk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});